DjangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views

from core.views import AddProduct, ProductView, UploadView

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/badges/<int:user_id>/', views.UserBadgeList.as_view(), name='user_badges_api'),
    path('upload/', AddProduct.addProduct, name='addProduct'),
    path('success/', UploadView.success, name='success'),
    path('track_product_click/<pk>/', ProductView.track_product_click, name='track_product_click'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoTestTechnique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views

from core.views import AddProduct, ProductView, UploadView

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/badges/<int:user_id>/', views.UserBadgeList.as_view(), name='user_badges_api'),
    path('upload/', AddProduct.addProduct, name='addProduct'),
    path('success/', UploadView.success, name='success'),
    path('track_product_click/<pk>/', ProductView.track_product_click, name='track_product_click'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import (
    UploadView,
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    ProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
)
from core import views

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<pk>/', ProductView.as_view(), name='product'),

    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),

    
]

templates/add_product.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajouter un produit</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <style>
        /* Styles pour le formulaire */
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
        }
        label {
            font-weight: bold;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-control {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .btn-primary {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    
    <div class="container">
        <p class="note note-primary">
            <strong>Note:</strong> <strong>Assurez vous</strong> que votre modèle porte l'extension .gltf.
            Vous devez l'envoyer sous sa forme compresser avec les fichiers directement à la racine.
          </p>
        <h2>Ajouter un modèle</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.item_name.id_for_label }}">Nom du produit:</label>
                <input type="text" name="item_name" id="item_name" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.price.id_for_label }}">Prix:</label>
                <input type="number" name="price" id="price" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.file.id_for_label }}">Fichier:</label>
                <input type="file" name="file" id="file" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.img.id_for_label }}">Image:</label>
                <input type="file" name="img" id="img" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="{{ form.discount_price.id_for_label }}">Prix réduit (facultatif):</label>
                <input type="number" name="discount_price" id="discount_price" class="form-control">
            </div>
            
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Description:</label>
                <textarea name="description" id="description" class="form-control" rows="4" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Ajouter le modèle</button>
        </form>
    </div>
</body>
</html>

templates/base.html
{% load static %}

{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fody Slider</title>
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
    <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style3D.css' %}" rel="stylesheet">


  </head>     

  <body>
    
    {% block content %}
    {% endblock content %}

     <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Django test technique</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          
          </li>
        </ul>
        {% for badge in user_badges %}
                  <span class="badge badge-pill {% if badge.label == 'start' %} danger-color  {% elif badge.label == 'Collector' %} primary-color{% else %} warning-color {% endif %}">{{ badge.label }}</span>

                {% empty %}
                    <li>Aucun badge</li>
                {% endfor %}
        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          
         
            {% if user.is_authenticated %}
            <li class="nav-item">
              
                <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                {% if request.user|cart_item_count != 0 %}
                  <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                {% endif %}
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
            </li>
            <li class="nav-item">
                 <a class="nav-link waves-effect">
                Hi {{ user.username }}!
                </a>
                
            </li>
             </li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'addProduct' %}"> Ajouter un model 3D</a>
            </li>
             </li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'logout' %}"> Deconnexion</a>
            </li>
            {% else %}
             </li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'login' %}"> Connexion</a>
            </li>
            {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
  <div class="mt-5 pt-4">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    </div>

    {% include "script.html" %}

    {% block extra_script %}
    {% endblock extra_script %}
    
  </body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

<main >
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout formulaire</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
                <label for="address" class="">Addresse</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.apartment_address }}
                <label for="address-2" class="">Addresse 2 (optionel)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Pays</label>
                  {{ form.country }}
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">L'adresse de livraison est la même que sur ma facture</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Savegarder</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>
             
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continuer</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

          <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Votre panier</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
              </div>
              <span class="text-muted">{{ order_item.get_final_price }}</span>
            </li>
            {% endfor %}
           

            {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promotion</h6>
                <small>EXEMPLE</small>
              </div>
              <span class="text-success">-$0</span>
            </li> {% endcomment %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>{{ order.get_total_price }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/footer.html
<!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">


    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

    
      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<section id="tranding">
  <div class="container">
    <h1 class="text-center section-heading">Gallery d'Art 3D</h1>
  </div>
  <div class="container">
    <div class="swiper tranding-slider">
      <div class="swiper-wrapper">
       
        {% for item in object_list %}
        <!-- Slide-start -->
        <div class="swiper-slide tranding-slide">
          <div class="tranding-slide-img">
            <img src="{{item.img}}" class="card-img-top"
                  alt="">
          </div>
          <div class="tranding-slide-content" style="margin-left:20px; margin-top:20px;">
            <h2 class="food-name" style="color: white;">
              <strong>Artiste</strong>
              <h3>{{item.views}} vue(s)</h3>

            </h2>
            <h2>

              <span class="badge badge-dark">{{item.user}}</span>
            </h2>
            <div class="tranding-slide-content-bottom">
              <h2 class="food-name">
                <a href="{% url 'track_product_click' item.pk %}" class="dark-grey-text">
                  <h2><span class="badge badge-primary">{{item.item_name}}</span></h2>

                </a>
              </h2>
              <strong>
                
                
              </strong>
            </div>

          </div>
        </div>
        <!-- Slide-end -->
        {% endfor %}

      </div>

      <div class="tranding-slider-control">
        <div class="swiper-button-prev slider-arrow">
          <ion-icon name="arrow-back-outline"></ion-icon>
        </div>
        <div class="swiper-button-next slider-arrow">
          <ion-icon name="arrow-forward-outline"></ion-icon>
        </div>
      </div>

    </div>
  </div>
</section>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fody Slider</title>
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">


  </head>

  <body>
    <section id="tranding">
      <div class="container">
        <h3 class="text-center section-subheading">- Django Test technique -</h3>
        <h1 class="text-center section-heading">Gallery d'Art 3D</h1>
      </div>
      <div class="container">
        <div class="swiper tranding-slider">
          <div class="swiper-wrapper">
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-1.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$20</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Special Pizza
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-2.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$20</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Meat Ball
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-3.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$40</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Burger
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-4.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$15</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Frish Curry
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-5.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$15</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Pane Cake
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-6.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$20</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Vanilla cake
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
            <!-- Slide-start -->
            <div class="swiper-slide tranding-slide">
              <div class="tranding-slide-img">
                <img src="images/tranding-food-7.png" alt="Tranding">
              </div>
              <div class="tranding-slide-content">
                <h1 class="food-price">$8</h1>
                <div class="tranding-slide-content-bottom">
                  <h2 class="food-name">
                    Straw Cake
                  </h2>
                  <h3 class="food-rating">
                    <span>4.5</span>
                    <div class="rating">
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                      <ion-icon name="star"></ion-icon>
                    </div>
                  </h3>
                </div>
              </div>
            </div>
            <!-- Slide-end -->
          </div>

          <div class="tranding-slider-control">
            <div class="swiper-button-prev slider-arrow">
              <ion-icon name="arrow-back-outline"></ion-icon>
            </div>
            <div class="swiper-button-next slider-arrow">
              <ion-icon name="arrow-forward-outline"></ion-icon>
            </div>
            <div class="swiper-pagination"></div>
          </div>

        </div>
      </div>
    </section>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script src="script.js"></script>
  </body>

</html>

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Your Cart</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">nom</th>
            <th scope="col">prix</th>
            <th scope="col">quantité</th>
            <th scope="col">Total prix</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.item_name }}</td>
            <td>
            {% if order_item.item.discount_price %}
                <del>${{ order_item.item.price}}</del> 
                ${{ order_item.item.discount_price }}
            {% else %}
                ${{ order_item.item.price}}
            {% endif %}

            </td>
            <td>
                <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_discount_item_price }} 
                <span class="badge badge-success" >Saved ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price}}
            {% endif %}
             <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>

            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Ton panier est vide</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="/" class="btn btn-primary float-right">Continuer</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.get_total_price %}
        <tr>
            <td colspan="4"><b>Total Order Price</b></td>
            <td>${{ object.get_total_price }}</td>
        </tr>
         <tr>
            <td colspan="5">
                <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                <a href="/" class="btn btn-primary float-right">Continuer</a>
            </td>
        </tr>
        
        {% endif %}
        
        </tbody>
    </table>

        </div>
    </div>
</main>

{% endblock content %}

templates/product.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <div id="aSide">

            <!-- 3D objsect -->
            <!-- This inserts the 3D object inside the aside container -->
              <model-viewer src="/extracted/{{object.id}}/scene.gltf" alt="VR Headset" auto-rotate camera-controls ar ios-src="/models/eye/scene.gltf">
              </model-viewer>
        </div>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge black mr-1">{{ object.user }}</span>
              </a>
              
            </div>

            <p class="lead">

            {% if object.discount_price %}
              <span class="mr-1">
              <del>${{ object.price }}</del>
              </span>
              <span style="color : red;">${{ object.discount_price }}</span>
            {% else %}
             <span>${{ object.price }}</span>
            {% endif %}

            </p>

            <p class="lead font-weight-bold">{{ object.item_name }}</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Ajouter au panier
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >retirer du panier
                <i class="fas fa-trash ml-1"></i>
            </a>
           

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/success.html
<!-- success.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bravooo, votre modèle a bien été enregistré !</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
</head>
<body>
    <p class="note note-success">
        Bravooo, votre modèle a bien été enregistré !
      </p>
    <a href="{% url 'addProduct' %}">Enregister un nouveau modèle</a>
</body>
</html>